### ISSUE TITLE
need to compile with java 7 or preferably 6.

### ISSUE THREAD

**Issue by eostermueller** [eostermueller/heapSpank#16]

**Comment by kiplandiles** [comment]
I agree. Most of my systems are still running Java7 and heapSpank errors with Unsupported major.minor version 52.0.

**Comment by eostermueller** [comment]
I just added a new release compiled with java 1.6.  Would you give it a try and let me know how it goes?

**Comment by kiplandiles** [comment]
Almost.
My JDK version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Partial process list of java ...

`glassfi+  2604     1  4 Apr06 ?        01:21:11 /usr/java/jdk1.7.0_80/bin/java -cp /usr/share/glassfish3/glassfish/modules/glassfish.jar`

Result

`java -jar heapSpank-0.09.jar 2604`
heapSpank: Attempting to load config class [com.github.eostermueller.heapspank.leakyspank.console.ApacheCommonsConfigFile]
heapSpank: loaded config [com.github.eostermueller.heapspank.leakyspank.console.ApacheCommonsConfigFile@7a4cbcaf]
heapSpank: Looking for tools.jar in/around java.home [/usr/java/jdk1.7.0_80/jre]
heapSpank: Candidate locations for tools.jar:
heapSpank: Exists? false Path: /usr/java/jdk1.7.0_80/jre/lib/tools.jar

heapSpank: Exists?  true Path: /usr/java/jdk1.7.0_80/lib/tools.jar

heapSpank: Exists? false Path: /usr/java/jdk1.7.0_80/Classes/classes.jar

heapSpank: Using [/usr/java/jdk1.7.0_80/lib/tools.jar]
com.github.eostermueller.heapspank.leakyspank.tools.ProcessIdDoesNotExist: JVM process id (pid) not found [2604]
	at com.github.eostermueller.heapspank.leakyspank.tools.VirtualMachineWrapper.<init>(VirtualMachineWrapper.java:70)
	at com.github.eostermueller.heapspank.leakyspank.console.LeakySpankConsole.init(LeakySpankConsole.java:225)
	at com.github.eostermueller.heapspank.leakyspank.console.LeakySpankConsole.main(LeakySpankConsole.java:55)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.github.eostermueller.heapspank.leakyspank.tools.VirtualMachineWrapper.<init>(VirtualMachineWrapper.java:61)
	... 2 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:213)
	... 7 more


JVM process id (pid) not found [2604]

**Comment by kiplandiles** [comment]
Disregard my previous comment. Java was running as user glassfish so running as that user worked. I was running as root before.
